### ISSUE TITLE
Support for armhf ?

### ISSUE THREAD

**Issue by dirkcjelli** [RexOps/repositorio#5]
Hi, 

I just tried to install repositor.io on a armhf-based device (Cubietruck), using the installer shellscript but got the following:

`W: Failed to fetch http://rex.linux-files.org/debian/dists/wheezy/rex/binary-armhf/Packages`

Would it be possible to add support for armhf ?

**Comment by krimdomu** [comment]
Hi,

well it adds the rex repositories for the dependency to Mojolicious. Mojolicious is a pure perl library so i think it would be possible. But we have to package Mojolicious for this architecture first.

You can download the installer script and modify it, so that it doesn't add the rex repository. If you're lucky the Mojolicious version shipped with your debian release is new enough.

**Comment by krimdomu** [comment]
I've just checked the wheezy repository... There is Mojolicious 2.98... this is pretty old, i don't think that it will work with this.

But you can manually install a newer Mojolicious version via: 
```
curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -n Mojolicious
```

**Comment by dirkcjelli** [comment]
Worked :+1:  

:cool:
